- package.json
- src/db/Database.ts
- Adds a new public property "events" to the Database class.
- Supports three main events:
- create: when a new entity is created;
- update: when an existing entity is updated;
- delete: when an existing entity is deleted.
- Pre-requisite for #49, #54 
By adding events to the Database, it becomes possible to listen to when they occur:
```js
db.events.on('create', (modelName, prevEntity, nextEntity) => {
console.log('created a new entity', modelName)
})
```
Persistency and synchronization would use database events to know when to apply them to other database instances (i.e. in other clients, or to the server instance).
> Database: Supports events

- README.md
- src/factory.ts
- src/glossary.ts
- src/model/createModel.ts
- src/model/defineRelationalProperties.ts
- src/model/generateGraphQLHandlers.ts
- src/model/parseModelDefinition.ts
- src/model/updateEntity.ts
- src/utils/findPrimaryKey.ts
- test/db/events.test.ts
- test/model/toRestHandlers.test.ts
- test/primaryKey.test.ts
- test/relations/one-to-one.test.ts
- test/utils/findPrimaryKey.test.ts
- test/utils/generateGraphQLHandlers.test.ts
- test/utils/parseModelDefinition.test.ts
- Closes #71 
Consistently adopts the term _model definition_, not declaration. 
Now parsing of the model happens when its API is created (previously when each entity is created). This helps to extract metadata from the model without having to wait until an entity is created. 
Relations no longer have `refs`, instead are resolved from the parsed model (`oneOf`/`manyOf` still return a relational object) and the initial value used to query that relational entity.
> Parses model definition when creating the model API

- src/db/Database.ts
- src/glossary.ts
- test/typings/typings.ts
Previously, getAll returned the type `any[]`, even though it returned additional properties. Now, the entity type is correctly inferred (similar to `findFirst`, `findMany`, etc.).
> Add generic type to getAll

- test/tsconfig.json
- tsconfig.json
In tests `@mswjs/data` is imported from the lib folder.
It was giving a type error because the test folder was not include in tsconfig.
> chore: add @mswjs/data as a module

- src/db/Database.ts
- src/factory.ts
- src/glossary.ts
- src/model/createModel.ts
- src/model/defineRelationalProperties.ts
- src/model/generateRestHandlers.ts
- src/model/parseModelDefinition.ts
- src/model/updateEntity.ts
- src/query/executeQuery.ts
- src/query/paginateResults.ts
- src/utils/first.ts
- src/utils/isInternalEntity.ts
- src/utils/removeInternalProperties.ts
- test/db/events.test.ts
- test/extensions/sync.test.ts
- test/relations/one-to-one.test.ts
- test/typings/typings.ts
- test/utils/cleanEntity.test.ts
- test/utils/isInternalEntity.test.ts
- test/utils/parseModelDefinition.test.ts
- test/utils/removeInternalProperties.test.ts
In this PR I have removed all the internals from API.
To do so I have removed remove coupling of api with itself and add the map transformation on different method returns.
I have also removed the map from the rest handlers because it is already done in the api.
I have created a new `Entity` type, the public one, and replaced the old one with `InternalEntity`.
- Closes #41
- Separates entities in `Entity` and `InternalEntity`.
- Adds an enum type for internal entity properties (`__type`, `__primaryKey`, etc.).
- Removes internal entity properties from public entities (i.e. from `db[model].create()` return payload).
- Sets `primaryKey` on the `Relation` when it's defined by looking it up in the database for the referenced model.
- Resolves relational properties against the `Relation` with …
> feat: remove all internals from API model

- test/model/relationalProperties.test.ts
Added a test to check that relational properties which get defined on the entity are enumerable. Checks #78 (fix added in #67).
> Add test to assert enumerable relational properties

- src/errors/OperationError.ts
- src/factory.ts
- src/model/generateRestHandlers.ts
- test/model/toRestHandlers.test.ts
- test/utils/generateRestHandlers.test.ts
I have added filter parameters to the GET handler.
As described in the issue you can now do the following
`GET users?firstName=Kate&lastName=Moen`
close #69
> REST handlers: Supports query parameters to query entity by its properties

- test/regressions/02-handlers-many-of.test.ts
- test/relations/one-to-many.test.ts
- test/relations/one-to-one.test.ts
- Related to #92 
- Adds missing tests for updating a `manyOf` relational property with both entity and a compatible object.
> Adds integration tests for updating a "manyOf" relational property

- src/factory.ts
- src/glossary.ts
- src/model/generateGraphQLHandlers.ts
- test/model/toGraphQLSchema.test.ts
This allows to expose the schema directly, to be consumed for example by graphql-codegen - and in consequence by TypeScript (via generated types) or the Apollo Graphql VSCode extension (via an exported introspection schema)
As an example:
```ts
// src/mocks/db.ts
import { factory, primaryKey } from '@mswjs/data'
const db = factory({
post: {
id: primaryKey(String),
name: String,
title: String,
author: String,
content: String,
status: String,
created_at: String,
updated_at: String,
},
})
export const handlers = db.post.toHandlers('graphql')
export const schema = db.post.toSchema('graphql')
```
```js
// src/mocks/schema.js
require('ts-node/register')
module.exports = require('./db').schema
```
```yml
// codegen.yml
overwrite: true
schema: './src/mocks/schema.js'
documents: 'src/**/*.graphql' …
```
> expose graphql schema via `factory.toSchema`

- src/utils/isInternalEntity.ts
- test/db/drop.test.ts
`removeInternalProperties` determines internal properties by looking at the value's type and the value's sub-properties. For example, [here](https://github.com/mswjs/data/blob/aa6ca0a48453faf9cfffe2a53ba927ac847d95c0/src/utils/removeInternalProperties.ts#L25-L28). When the value is `null` for which `typeof null === 'object'` is true, the following exception is thrown.
```
TypeError: Cannot use 'in' operator to search for '__type' in null
9 |     return (
10 |     // value &&
> 11 |     glossary_1.InternalEntityProperty.type in value &&
|                                            ^
12 |         glossary_1.InternalEntityProperty.primaryKey in value);
13 | }
14 | exports.isInternalEntity = isInternalEntity;
at Object.isInternalEntity (lib/utils/isInternalEntity.js:11:44)
at …
```
> handle null value in db isInternalEntity

- package.json
- yarn.lock
- Fixes https://github.com/mswjs/msw/issues/832
- Originated from #106 
- The `msw` package is not pinned to the `latest` published version tag. This is rather permissive, but it should encourage the users to migrate to the latest version of `msw` and also rid this package from bumping the `msw` version on each minor release.
As #106 illustrates, there may be issues related to the application and `@mswjs/data` installing and using different versions of `msw`. Pinning the version to be the latest means that the data package always relies on the latest version and demands from the application to do so as well. 
Note that patch releases never contain breaking changes, so it should be safe to be ahead/behind in patch versions.
> Specifies the "latest" version of "msw" as a dependency

- README.md
- package.json
- src/glossary.ts
- src/query/compileQuery.ts
- src/query/executeQuery.ts
- src/query/paginateResults.ts
- src/query/queryTypes.ts
- src/query/sortResults.ts
- src/utils/removeInternalProperties.ts
- test/query/pagination.test.ts
- test/typings/typings.ts
- test/utils/removeInternalProperties.test.ts
- tsconfig.json
- yarn.lock
- Closes #102 
It is now possible to sort query results of the `.findMany()` method using the `orderBy` property on the query:
```js
db.post.findMany({
where: {
category: {
equals: 'Science',
},
},
take: 10,
orderBy: {
title: 'asc',
},
})
```
Provides support for:
- Basic sorting by direct properties.
- Sorting by multiple criteria.
- Sorting by relational properties. 
- Only 1 known entity key can be specified in the sort criteria object. Use the list of criteria for multi-criteria sort.
> Supports sorting with the "orderBy" option on ".findMany()"

- src/utils/isInternalEntity.ts
- src/utils/isObject.ts
- src/utils/removeInternalProperties.ts
- test/utils/isObject.test.ts
- Fixes #94 
- A prerequisite for #98, #113 
- Asserts that the given value is an object during the `isInternalEntity` check.
This prevents the `isInternalEntity` check to throw an exception when handling non-object types (still possible on runtime with the nested properties in model declarations).
```
TypeError: Cannot use 'in' operator to search for '__type' in "some value"
```
> isInternalEntity: Assert the value is an object

- src/model/defineRelationalProperties.ts
- src/model/parseModelDefinition.ts
- src/relations/Relation.ts
- src/utils/definePropertyAtPath.ts
- test/model/create.test.ts
- test/model/relationalProperties.test.ts
- test/relations/Relation.test.ts
- test/utils/definePropertyAtPath.test.ts
- test/utils/parseModelDefinition.test.ts
This PR moves the internal representation of property paths from dot notation strings to arrays of strings.
This allows us to continue using and benefitting from `lodash/set`, and also support dots in model properties, eg:
```ts
export const db = factory({
user: {
'employee.id': primaryKey(() => 'abc-123'),
}
})
```
Closes #149
> Support model properties with dots in them

- .github/workflows/main.yml
This should help in observability of the local/CI environments differences.
> chore(ci): add "versions" step to CI

- README.md
- src/glossary.ts
- src/index.ts
- src/model/createModel.ts
- src/model/defineRelationalProperties.ts
- src/model/generateRestHandlers.ts
- src/model/parseModelDefinition.ts
- src/model/updateEntity.ts
- src/nullable.ts
- src/primaryKey.ts
- src/query/compileQuery.ts
- src/relations/Relation.ts
- src/utils/isModelValueType.ts
- test/model/create.test-d.ts
- test/model/create.test.ts
- test/model/relationalProperties.test.ts
- test/model/update.test-d.ts
- test/model/update.test.ts
- test/model/updateMany.test.ts
- test/query/boolean.test.ts
- test/query/date.test.ts
- test/query/number.test.ts
- test/query/string.test.ts
- test/relations/Relation.test.ts
- test/relations/many-to-one.test.ts
- test/relations/one-to-many.test.ts
- test/relations/one-to-one.test.ts
- test/utils/isModelValueType.test.ts
closes #142 
New `nullable` function provides an API for defining nullable properties
as well as nullable relations.
The arguments passed to `nullable` are identical to those passed to
factory when the property is not nullable. This means `nullable` should
feel natural to use for users familiar to the project.
For example to define a nullable property the user passes the factory
function they would use to normally define the property to `nullable`
when defining the db. This matches the `primaryKey` method as a bonus.
To define a nullable relation they would pass the `oneOf` or `manyOf`
function with the model name directly to `nullable`.
The model API methods are all typed to know when it's possible for a
property to be null, and an invariant violation is raised for js users
who try to …
> Add support for null property values

- src/glossary.ts
- test/typings/relations.test-d.ts
```ts
const db = factory({
user: {
id: primaryKey(String),
country: oneOf('country'),
stats: {
revision: oneOf('revision'),
},
},
country: {
code: primaryKey(String),
},
revision: {
id: primaryKey(String),
updatedAt: Number,
},
})
const user = db.user.create()
user.country.code.toUpperCase()
user.stats.revision?.id // TypeError
user.stats.revision?.updatedAt.toFixed() // TypeError
```
A nested relationship is not annotated because the `Value` generic for the nested properties passed the incorrect `Dictionary` generic:
https://github.com/mswjs/data/blob/0970e7ed5a9094d6618ed6563f8bb3a00d5c9ecc/src/glossary.ts#L216
This causes the `user.stats.revision` to be type of `Value<undefined, OneOf<...>>`. That `undefined` means that the relationship value cannot be inferred when using …
> fix(types): annotate nested relationships

- src/model/updateEntity.ts
- src/utils/spread.ts
- test/relations/one-to-one.test.ts
- test/utils/spread.test.ts
- Fixes #170
- Originated from #167 
- Adds the `spread` utility that preserves object getters/setters.
- Adds missing integration tests to `one-to-one` relationship test suite.
> fix(updateEntity): preserve relational getters when spreading "entityChunk"

- src/utils/isModelValueType.ts
- test/model/create.test.ts
- test/utils/isModelValueType.test.ts
- Fixes #165
I stumbled upon an issue mentioned in https://github.com/mswjs/data/issues/165 when using an array of objects for one of the fields of the model. After downgrading the version to v0.7.2 it worked fine. 
If it's a regression as mentioned in https://github.com/mswjs/data/issues/165#issuecomment-974645341, removing the additional check for primitive values in case of an array should suffice. However, I'm not sure if it could affect the feature of nullable properties from https://github.com/mswjs/data/pull/143.
I just started using the library and I'm not fully aware of some parts of it as well as the internals 😉  Let me know if I'm missing something. With some guidance, I believe I could fix that one 😄 
Btw. Huge thanks for maintaining `msw` and making the process of creating …
> fix(create): allow the field with type array to be an array of objects

- src/glossary.ts
- test/model/getAll.test-d.ts
- test/model/relationalProperties.test-d.ts
- test/query/pagination.test.ts
- test/relations/one-to-many.test.ts
- test/relations/one-to-one.test.ts
- test/typings/relations.test-d.ts
When a model is created any property that does not have an initial value uses the factory method to create one. Since the factories are typed to only allow certain primitive values it is not possible for those values to ever be `undefined`. For relational properties created through `oneOf` and `manyOf` this is not the case however, if they are not provided an initial value they are `undefined`.
For example in the following snippet:
```typescript
const db = factory({
user: {
id: primaryKey(String),
},
post: {
id: primaryKey(String),
author: oneOf('user'),
},
})
const post = db.user.create();
```
`post.author` is `undefined` but it is not included in the property type.
This PR adds `undefined` to the possible value types for relationships.
> fix(types): relationships can be undefined

- src/glossary.ts
- test/model/relationalProperties.test-d.ts
I made a mistake when updating #158 after we merged #143, it is not actually possible for nullable relationships to be `undefined`, they are `null` instead. Sorry I let that slip by!
This is purely for proper annotation similarly to #158 
It is not possible for the value of nullable relations to be undefined because:
- if the relation does not have an initial value it defaults to null.
- it is not possible to update the relation's value to be undefined after the fact.
> fix(types): nullable relations are never undefined

- .github/FUNDING.yml
Use the [MSW GitHub Sponsors profile](https://github.com/sponsors/mswjs) for the "Sponsor" button.
> chore: use mswjs for GitHub sponsors

- src/query/executeQuery.ts
- src/utils/safeStringify.ts
- test/relations/bi-directional.test.ts
closes #139 
When passing an object with circular references to `update` the `executeQuery` function fails: it passes the `query` object to `JSON.stringify` which throws a "cyclic object value" exception.
Circular references are created when a bi-directional relationship is made. For example:
```typescript
const db = factory({
user: {
id: primaryKey(String),
posts: manyOf('post'),
},
post: {
id: primaryKey(String),
author: oneOf('user')
},
});
const author = db.user.create({ id: 'user-1' })
const post = db.post.create({ id: 'post-1', author })
const nextAuthor = db.user.update({
where: { id: { equals: author.id } },
data: { posts: [post] },
})
```
If an entity that has been set up this way is passed to `update` it fails because of the above:
```typescript
db.post.update({
where: { id: { …
```
> fix(executeQuery): support circular references when updating entities

- src/model/defineRelationalProperties.ts
- src/relations/Relation.ts
- test/model/findMany.test.ts
- test/relations/one-to-many.test.ts
- Fixes #199 
- Non-nullable `manyOf` relation now returns an empty array `[]` when it has no value (previously: `undefined`).
- Other behaviors are intact. Nullable relations _always_ return `null` when they have no value.
> feat(manyOf): return empty array for non-nullable without value

- src/glossary.ts
- test/model/relationalProperties.test-d.ts
This PR fixes the typings to match the behavioural update in https://github.com/mswjs/data/pull/201 (#199).
> fix(manyOf): exclude undefined from non-nullable without value

- README.md
Hello! 
In January 2022 there was an incident with the original maintainer of `faker.js`, and there is a new community-maintained library for it -- more context on all that [here](https://fakerjs.dev/about/announcements/2022-01-14.html).
This PR updates references to Faker in the readme to point to the new GitHub repository, and for code samples to use the updated `@faker-js/faker` dependency.
> Update Faker references in README

- src/comparators/string.ts
- src/query/queryTypes.ts
- test/comparators/number-comparators.test.ts
- test/comparators/string-comparators.test.ts
- test/model/toGraphQLSchema.test.ts
Adds the ability to perform greater than, greater than or equal to, less than and less than or equal to operators on string data values.
In addition, fixed a typo in the number test suite for the description of `lt` comparators.
Discussion: https://github.com/mswjs/data/discussions/244
> feat(query): add gt/gte/lt/lte to string comparators

- src/query/queryTypes.ts
Fixes https://github.com/mswjs/data/issues/250
> fix: make "EntityType" type compatible with objects

- src/model/generateRestHandlers.ts
- test/utils/generateRestHandlers.test.ts
Removes usage of URL constructor in `createUrlBuilder` which is used for generating REST handlers.
Approach with strings concatenation allows us to use relative paths without specific hostnames, provide prefixes, and also use parameters in the baseUrl that will be handled by MSW.
I also added removing trailing slashes from the baseUrl, as previously it could be passed with and without it and won't affect the result, so I keep it like it was to avoid breaking changes.
Additionally updated tests for the function: removed the leading slash. Because `buildUrl` calls inside `generateRestHandlers` have no leading shashes so tests weren't exactly correct.
(ref: #267)
> feat: support relative paths when generating rest handlers

- package.json
- src/db/Database.ts
- src/extensions/sync.ts
- src/model/generateGraphQLHandlers.ts
- src/model/generateRestHandlers.ts
- src/utils/iteratorUtils.ts
- test/db/events.test.ts
- yarn.lock
I faced the same problem as https://github.com/mswjs/http-middleware/issues/27.
This problem caused by `strict-event-emitter` version.
In another repositories uses higher than v0.4.3 so version but in this repository one is v0.2.0.
New API named `Emitter` is used from v0.3.2 and `StrictEventEmitter` was removed from v0.4.0.
> feat: upgrade strict-event-emitter to 0.5.0

- README.md
The package is supposed to be a devDependency; yarn add flag was incorrect, installs it as a dependency.
> docs: fix typo in yarn install options

- src/db/Database.ts
> fix: add random number to db id seed

- src/factory.ts
- src/glossary.ts
- src/model/createModel.ts
- src/model/getDefinition.ts
- src/model/parseModelDefinition.ts
- src/model/updateEntity.ts
- src/nullable.ts
- test/model/create.test.ts
- test/model/update.test.ts
This PR is for supporting nullable objects without a getter function (mentioned in [issue 203](https://github.com/mswjs/data/issues/203))
I took some inspiration from @roertbb solution, but solved it a little bit differently. I haven't changed the ModelValueType definition but rather made a new NullableObject class that accepts a value of the type NestedModelDefinition, since this is in fact what it should receive. It also accepts a second arg that indicates if the NullableObject should default to null (I made it so that the complete object definition will always be given while creating an instance of the class)
In general, I think that @kettanaito request [here](https://github.com/mswjs/data/issues/203#issue-1197709742) to implement it without a getter function makes a lot of sense as it …
> feat: created nullable object option without getter

- .github/workflows/ci.yml
- .github/workflows/release.yml
- package.json
- src/model/generateGraphQLHandlers.ts
- src/model/generateRestHandlers.ts
- test/model/toGraphQLSchema.test.ts
- test/regressions/02-handlers-many-of.test.ts
- tsconfig.json
- yarn.lock
- Fixes #289 
Marking this as a `feat` since it also bumps the `graphql` dependency to have type-compatible with MSW 1.
> feat: pin msw to 1.0.0

- package.json
- src/glossary.ts
- src/model/generateGraphQLHandlers.ts
- src/model/generateRestHandlers.ts
- test/db/events.test.ts
- test/jest.config.ts
- test/model/toRestHandlers/basic.test.ts
- test/model/toRestHandlers/primary-key-number.test.ts
- test/regressions/02-handlers-many-of.test.ts
- test/tsconfig.json
- test/typings/tsconfig.json
- test/utils/generateRestHandlers.test.ts
- test/utils/updateEntity.test.ts
- test/vitest.config.ts
- test/vitest.setup.ts
- tsconfig.json
- yarn.lock
- Migrates to MSW 2.0.
- Uses Vitest as the test runner instead of Jest.
> feat!: migrate to msw 2.0

- tests/hooks/delete.test.ts
> test: add tests for the "delete" hook

- README.md
- src/collection.ts
- src/errors.ts
- src/extensions/persist.ts
- src/index.ts
- src/relation.ts
- tests/relations/one-to-many.test.ts
- tests/relations/one-to-one.test.ts
- Closes #307
- Documents error handling in `README.md`.
- Implements a `RelationError` class.
- Refactors the `OperationError` to include `code` instead of specific operation names.
- Validates unique relations for the lack of other owners referencing the same foreign record(s) (for one-way unique relations).
- Adds missing tests for unique relations.
- one-to-many unique relations tests are present. The many-to relations cannot be unique by design; they implied that many records may reference many other records.
> fix: implement `RelationError`, improve unique relations validation

- README.md
- extensions/package.json
- package.json
- Fixes #325 
Extensions should be imported from their own entrypoints to (1) have a minimal footprint on the user's bundle; (2) be self-contained (think browser/node-only extensions).
> fix: add granular exports for extensions
